-- 2021.06.17

-- INDEX : 검색을 빠르게 하기 위한 객체
-- 물리적인 저장 공간이 필요
-- 생성 시간이 필요
-- 많은 index는 DML 작업이 많은 경우 성능 저하가 온다

-- EMP01 테이블을 복사 -> 로우들을 계속 복사
DROP TABLE EMP01;
CREATE TABLE EMP01
AS SELECT * FROM EMP
;

INSERT INTO EMP01 SELECT * FROM EMP;
SELECT * FROM EMP01;

INSERT INTO EMP01 SELECT * FROM EMP01;
INSERT INTO EMP01 (EMPNO, ENAME) VALUES (7777, 'KING');
INSERT INTO EMP01 (EMPNO, ENAME) VALUES (7777, 'SON');

SELECT * FROM EMP01 WHERE ENAME = 'SON';






-- EMP01 테이블에 ENAME 컬럼을 INDEX 설정
CREATE INDEX INDEX_EMP01_ENAME 
ON EMP01(ENAME)
;
